from django.utils import translation

# Переводы для шаблонов
TRANSLATIONS = {
    'en': {
        'Главная': 'Home',
        'Об университете': 'About the university',
        'Документация': 'Documentation',
        'Процессы и инструкции': 'Processes and instructions',
        'Контакты и карта': 'Contacts and map',
        'Обратная связь': 'Feedback',
        'Часто задаваемые вопросы': 'Frequently asked questions',
        'Уроки': 'Lessons',
        'Настройки': 'Settings',
        'Поддержка': 'Support',
        'Выход': 'Exit',
        'Доброе утро': 'Good morning',
        'Добрый день': 'Good afternoon',
        'Добрый вечер': 'Good evening',
        'Логин': 'Login',
        'Пароль': 'Password',
        'Забыли пароль?': 'Forgot password?',
        'Продолжить': 'Continue',
        'Начать поиск': 'Start the search',
        'Ничего не найдено': 'Nothing found',
        'Задайте свой вопрос': 'Ask your question',
        'Узнайте больше о внутренних процессах': 'Learn more about internal processes',
        'Процессы': 'Processes',
        'Инструкции': 'Instructions',
        'Процесс': 'Process',
        'Инструкция': 'Instruction',
        'Язык интерфейса': 'Interface Language',
        'Выберите язык для отображения интерфейса сайта': 'Choose the language for displaying the site interface',
        'Сохранить изменения': 'Save changes',
        'Язык успешно изменен': 'Language successfully changed',
        # Feedback form
        'Обратная связь': 'Feedback',
        'Если у вас есть предложения, замечания по работе сайта или вопросы — отправьте их через форму ниже. Мы ответим как можно быстрее.': 'If you have suggestions, comments about the website or questions — send them through the form below. We will respond as quickly as possible.',
        '1. Кому направить?': '1. Who to address?',
        '2. Тип обращения': '2. Type of request',
        '3. Тема обращения': '3. Subject',
        'Введите тему своего обращения': 'Enter the subject of your request',
        '4. Сообщение': '4. Message',
        'Опишите ваше обращение как можно подробнее...': 'Describe your request in as much detail as possible...',
        '5. Прикрепите файл': '5. Attach file',
        'Загрузить файл': 'Upload file',
        '6. Ваши контакты': '6. Your contacts',
        'Почта': 'Email',
        'Номер телефона': 'Phone number',
        'Отправить': 'Send',
        
        # Процессы и инструкции
        'Поиск процессов и инструкций': 'Search processes and instructions',
        'Все': 'All',
        'Процессы': 'Processes',
        'Инструкции': 'Instructions',
        'Процесс регистрации студентов': 'Student registration process',
        'Инструкция по использованию библиотеки': 'Library usage instructions',
        'Процесс подачи заявления на стипендию': 'Scholarship application process',
        'Инструкция по работе с электронной почтой': 'Email usage instructions',
        'Процесс записи на курсы': 'Course enrollment process',
        'Инструкция по доступу к онлайн-ресурсам': 'Online resources access instructions',
        
        # Карта и контакты
        'Контакты и карта': 'Contacts and map',
        'Наши контакты': 'Our contacts',
        'Телефон': 'Phone',
        'Электронная почта': 'Email',
        'Адрес': 'Address',
        'Режим работы': 'Working hours',
        'Понедельник - Пятница: 9:00 - 18:00': 'Monday - Friday: 9:00 - 18:00',
        'Суббота: 10:00 - 16:00': 'Saturday: 10:00 - 16:00',
        'Воскресенье: выходной': 'Sunday: closed',
        'Как нас найти': 'How to find us',
        
        # Обратная связь
        'Ваше имя': 'Your name',
        'Ваш email': 'Your email',
        'Тема сообщения': 'Message subject',
        'Ваше сообщение': 'Your message',
        'Отправить сообщение': 'Send message',
        'Спасибо за ваше сообщение! Мы ответим в ближайшее время.': 'Thank you for your message! We will reply soon.',
        'Если у вас есть предложения, замечания по работе сайта или вопросы — отправьте их через форму ниже. Мы ответим как можно быстрее.': 'If you have suggestions, comments about the website or questions - send them through the form below. We will respond as quickly as possible.',
        
        # FAQ
        'Поиск по вопросам': 'Search questions',
        'Категории': 'Categories',
        'Академические вопросы': 'Academic questions',
        'Технические вопросы': 'Technical questions',
        'Административные вопросы': 'Administrative questions',
        'Как подать заявление на поступление?': 'How to apply for admission?',
        'Какие документы необходимы для поступления?': 'What documents are required for admission?',
        'Как восстановить пароль от личного кабинета?': 'How to reset password for personal account?',
        'Где найти расписание занятий?': 'Where to find class schedule?',
        'Как связаться с преподавателем?': 'How to contact a teacher?',
        'Где получить справку об обучении?': 'Where to get a study certificate?',
        
        # Дополнительные тексты
        'Кампус': 'Campus',
        'На территории кампуса': 'On campus territory',
        'Множество аудиторий': 'Multiple classrooms',
        'Спорт Комплекс': 'Sports Complex',
        'Библиотека': 'Library',
        'Столовая': 'Canteen',
        'Студенческие общежития': 'Student dormitories',
        'Парковка': 'Parking',
        'Как нас найти': 'How to find us',
        'Все категории': 'All categories',
        'Нет результатов': 'No results',
        'Попробуйте изменить критерии поиска': 'Try changing search criteria',
        'Нет процессов и инструкций': 'No processes and instructions',
        'Попробуйте изменить критерии поиска или очистить фильтры': 'Try changing search criteria or clear filters',
        'В данный момент процессы и инструкции отсутствуют': 'Currently no processes and instructions available',
        'Скачать PDF': 'Download PDF',
        'Документы не найдены': 'Documents not found',
        'или очистить фильтры': 'or clear filters',
        'В данный момент документы отсутствуют': 'Currently no documents available',
        'Уроки не найдены': 'No lessons found',
        'Попробуйте изменить критерии поиска или выбрать другую категорию.': 'Try changing your search criteria or selecting another category.',
        'История': 'History',
        'Миссия': 'Mission',
        'Ценности': 'Values',
        'Руководство Университета': 'University Leadership',
        'Ректор': 'Rector',
        'Проректор': 'Vice-Rector',
        'Мы улучшаем мир посредством образования, исследований и предпринимательства.': 'We improve the world through education, research and entrepreneurship.',
        'Лидерство, Предпринимательство, Честность, Устойчивое развитие, Ответственность': 'Leadership, Entrepreneurship, Honesty, Sustainable development, Responsibility',
        'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum': 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
    },
    'kk': {
        'Главная': 'Басты бет',
        'Об университете': 'Университет туралы',
        'Документация': 'Құжаттама',
        'Процессы и инструкции': 'Процестер мен нұсқаулар',
        'Контакты и карта': 'Карта және контактілер',
        'Обратная связь': 'Кері байланыс',
        'Часто задаваемые вопросы': 'Жиі қойылатын сұрақтар',
        'Уроки': 'Сабақтар',
        'Настройки': 'Настройки',
        'Поддержка': 'Поддержка',
        'Выход': 'Шығу',
        'Доброе утро': 'Қайырлы таң',
        'Добрый день': 'Қайырлы күн',
        'Добрый вечер': 'Қайырлы кеш',
        'Логин': 'Логин',
        'Пароль': 'Құпия сөз',
        'Забыли пароль?': 'Құпия сөзді ұмыттыңыз ба?',
        'Продолжить': 'Жалғастыру',
        'Начать поиск': 'Іздеуді бастау',
        'Ничего не найдено': 'Ештеңе табылмады',
        'Задайте свой вопрос': 'Сұрағыңызды қойыңыз',
        'Узнайте больше о внутренних процессах': 'Ішкі процестер туралы көбірек біліңіз',
        'Процессы': 'Процестер',
        'Инструкции': 'Нұсқаулар',
        'Процесс': 'Процесс',
        'Инструкция': 'Нұсқаулық',
        'Язык интерфейса': 'Интерфейс тілі',
        'Выберите язык для отображения интерфейса сайта': 'Сайт интерфейсін көрсету үшін тілді таңдаңыз',
        'Сохранить изменения': 'Өзгерістерді сақтау',
        'Язык успешно изменен': 'Тіл сәтті өзгертілді',
        # Feedback form
        'Обратная связь': 'Кері байланыс',
        'Если у вас есть предложения, замечания по работе сайта или вопросы — отправьте их через форму ниже. Мы ответим как можно быстрее.': 'Егер сіздің ұсыныстарыңыз, сайттың жұмысы туралы ескертпелеріңіз немесе сұрақтарыңыз болса — оларды төмендегі форма арқылы жіберіңіз. Біз барынша тез жауап береміз.',
        '1. Кому направить?': '1. Кімге жіберу керек?',
        '2. Тип обращения': '2. Өтініш түрі',
        '3. Тема обращения': '3. Тақырыбы',
        'Введите тему своего обращения': 'Өтінішіңіздің тақырыбын енгізіңіз',
        '4. Сообщение': '4. Хабарлама',
        'Опишите ваше обращение как можно подробнее...': 'Өтінішіңізді мүмкіндігінше толық сипаттаңыз...',
        '5. Прикрепите файл': '5. Файл тіркеңіз',
        'Загрузить файл': 'Файл жүктеу',
        '6. Ваши контакты': '6. Сіздің байланыстарыңыз',
        'Почта': 'Электрондық пошта',
        'Номер телефона': 'Телефон нөмірі',
        'Отправить': 'Жіберу',
        
        # Процессы и инструкции
        'Поиск процессов и инструкций': 'Процестер мен нұсқауларды іздеу',
        'Все': 'Барлығы',
        'Процессы': 'Процестер',
        'Инструкции': 'Нұсқаулар',
        'Процесс регистрации студентов': 'Студенттерді тіркеу процесі',
        'Инструкция по использованию библиотеки': 'Кітапхананы пайдалану нұсқаулығы',
        'Процесс подачи заявления на стипендию': 'Стипендияға өтініш беру процесі',
        'Инструкция по работе с электронной почтой': 'Электрондық поштамен жұмыс нұсқаулығы',
        'Процесс записи на курсы': 'Курстарға жазылу процесі',
        'Инструкция по доступу к онлайн-ресурсам': 'Онлайн-ресурстарға қол жеткізу нұсқаулығы',
        
        # Карта и контакты
        'Контакты и карта': 'Байланыстар мен карта',
        'Наши контакты': 'Біздің байланыстар',
        'Телефон': 'Телефон',
        'Электронная почта': 'Электрондық пошта',
        'Адрес': 'Мекенжай',
        'Режим работы': 'Жұмыс режимі',
        'Понедельник - Пятница: 9:00 - 18:00': 'Дүйсенбі - Жұма: 9:00 - 18:00',
        'Суббота: 10:00 - 16:00': 'Сенбі: 10:00 - 16:00',
        'Воскресенье: выходной': 'Жексенбі: демалыс',
        'Как нас найти': 'Бізді қалай табуға болады',
        
        # Обратная связь
        'Ваше имя': 'Сіздің атыңыз',
        'Ваш email': 'Сіздің email',
        'Тема сообщения': 'Хабарлама тақырыбы',
        'Ваше сообщение': 'Сіздің хабарламаңыз',
        'Отправить сообщение': 'Хабарлама жіберу',
        'Спасибо за ваше сообщение! Мы ответим в ближайшее время.': 'Хабарламаңыз үшін рахмет! Біз жақын арада жауап береміз.',
        'Если у вас есть предложения, замечания по работе сайта или вопросы — отправьте их через форму ниже. Мы ответим как можно быстрее.': 'Егер сіздің ұсыныстарыңыз, сайттың жұмысы туралы ескертулеріңіз немесе сұрақтарыңыз болса - оларды төмендегі форма арқылы жіберіңіз. Біз мүмкіндігінше тезірек жауап береміз.',
        
        # FAQ
        'Поиск по вопросам': 'Сұрақтар бойынша іздеу',
        'Категории': 'Санаттар',
        'Академические вопросы': 'Академиялық сұрақтар',
        'Технические вопросы': 'Техникалық сұрақтар',
        'Административные вопросы': 'Әкімшілік сұрақтар',
        'Как подать заявление на поступление?': 'Түсуге өтініш қалай беруге болады?',
        'Какие документы необходимы для поступления?': 'Түсу үшін қандай құжаттар қажет?',
        'Как восстановить пароль от личного кабинета?': 'Жеке кабинеттің паролін қалай қалпына келтіруге болады?',
        'Где найти расписание занятий?': 'Сабақ кестесін қайдан табуға болады?',
        'Как связаться с преподавателем?': 'Оқытушымен қалай байланысуға болады?',
        'Где получить справку об обучении?': 'Оқу туралы анықтаманы қайдан алуға болады?',
        
        # Дополнительные тексты
        'Кампус': 'Кампус',
        'На территории кампуса': 'Кампус аумағында',
        'Множество аудиторий': 'Көптеген аудиториялар',
        'Спорт Комплекс': 'Спорт кешені',
        'Библиотека': 'Кітапхана',
        'Столовая': 'Асхана',
        'Студенческие общежития': 'Студенттік жатақханалар',
        'Парковка': 'Тұрақ',
        'Как нас найти': 'Бізді қалай табуға болады',
        'Все категории': 'Барлық санаттар',
        'Нет результатов': 'Нәтиже жоқ',
        'Попробуйте изменить критерии поиска': 'Іздеу критерийлерін өзгертіп көріңіз',
        'Нет процессов и инструкций': 'Процестер мен нұсқаулар жоқ',
        'Попробуйте изменить критерии поиска или очистить фильтры': 'Іздеу критерийлерін өзгертіп көріңіз немесе сүзгілерді тазалаңыз',
        'В данный момент процессы и инструкции отсутствуют': 'Қазіргі уақытта процестер мен нұсқаулар жоқ',
        'Скачать PDF': 'PDF жүктеп алу',
        'Документы не найдены': 'Құжаттар табылмады',
        'В данный момент документы отсутствуют': 'Қазіргі уақытта құжаттар жоқ',
        'История': 'Тарих',
        'Миссия': 'Миссия',
        'Ценности': 'Құндылықтар',
        'Руководство Университета': 'Университет басшылығы',
        'Ректор': 'Ректор',
        'Проректор': 'Проректор',
        'Мы улучшаем мир посредством образования, исследований и предпринимательства.': 'Біз білім беру, зерттеу және кәсіпкерлік арқылы әлемді жақсартамыз.',
        'Лидерство, Предпринимательство, Честность, Устойчивое развитие, Ответственность': 'Көшбасшылық, Кәсіпкерлік, Адалдық, Тұрақты даму, Жауапкершілік',
        'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum': 'Lorem Ipsum - бұл баспа және теру өнеркәсібінің қарапайым жалған мәтіні. Lorem Ipsum 1500-шы жылдардан бастап өнеркәсіптің стандартты жалған мәтіні болып келеді, белгісіз баспагер галлейді алып, оны үлгі кітабын жасау үшін араластырған кезде. Ол бес ғасырдан ғана емес, сонымен қатар электронды теру саласына да секіріп өтті, негізінен өзгеріссіз қалды. Ол 1960-шы жылдары Lorem Ipsum үзінділерін қамтитын Letraset парақтарының шығарылуымен және жақында Aldus PageMaker сияқты үстел баспа бағдарламаларымен Lorem Ipsum нұсқаларын қосумен танымал болды',
    }
}

def get_translation(text, language='ru'):
    """Простая функция перевода"""
    if language == 'ru' or language not in TRANSLATIONS:
        return text
    return TRANSLATIONS.get(language, {}).get(text, text)

def language_context(request):
    """Контекст процессор для переводов"""
    current_language = request.session.get('django_language', 'ru')
    
    def trans(text):
        return get_translation(text, current_language)
    
    return {
        'current_language': current_language,
        'trans': trans,
        'LANGUAGE_CODE': current_language,
    }