# Generated by Django 5.1.2 on 2025-10-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Опционально. Инструкция в формате PDF', null=True, upload_to='instructions/pdfs/', verbose_name='PDF'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='video',
            field=models.FileField(blank=True, help_text='Опционально. Поддерживаемые форматы: MP4, AVI, MOV, WMV', null=True, upload_to='instructions/videos/', verbose_name='Видео'),
        ),
    ]
