# Generated by Django 5.1.2 on 2025-10-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_instruction_pdf_file_instruction_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='about/', verbose_name='Картинка истории 2'),
        ),
        migrations.AddField(
            model_name='history',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='about/', verbose_name='Картинка истории 3'),
        ),
        migrations.AlterField(
            model_name='history',
            name='image',
            field=models.ImageField(blank=True, upload_to='about/', verbose_name='Картинка истории 1'),
        ),
    ]
