# Generated by Django 4.2.7 on 2025-07-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_documentcategory_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'ordering': ['order_index', 'name'], 'verbose_name': 'Категория документов', 'verbose_name_plural': 'Категории документов'},
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='order_index',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
    ]
