# Generated by Django 5.1.2 on 2025-10-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_history_image_2_history_image_3_alter_history_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='pdf_file_en',
            field=models.FileField(blank=True, help_text='Опционально. Инструкция в формате PDF для английского языка', null=True, upload_to='instructions/pdfs/', verbose_name='PDF (English)'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='pdf_file_kk',
            field=models.FileField(blank=True, help_text='Опционально. Инструкция в формате PDF для казахского языка', null=True, upload_to='instructions/pdfs/', verbose_name='PDF (Қазақша)'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Опционально. Инструкция в формате PDF для русского языка', null=True, upload_to='instructions/pdfs/', verbose_name='PDF (Русский)'),
        ),
    ]
