# Generated by Django 5.1.2 on 2025-10-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_position_instruction_allowed_positions_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcategory',
            name='allowed_positions',
            field=models.ManyToManyField(blank=True, related_name='documents', to='main.position', verbose_name='Доступные должности'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='allowed_positions',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='main.position', verbose_name='Доступные должности'),
        ),
    ]
