# Generated by Django 4.2.7 on 2025-08-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_faqcategory_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание (English)'),
        ),
        migrations.AddField(
            model_name='document',
            name='description_kk',
            field=models.TextField(blank=True, verbose_name='Описание (Қазақша)'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_en',
            field=models.FileField(blank=True, upload_to='documents/', verbose_name='Файл (English)'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_kk',
            field=models.FileField(blank=True, upload_to='documents/', verbose_name='Файл (Қазақша)'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (English)'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_kk',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (Қазақша)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/', verbose_name='Файл (Русский)'),
        ),
    ]
