# Generated by Django 5.1.2 on 2025-10-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_documentcategory_allowed_positions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='allowed_positions',
            field=models.ManyToManyField(blank=True, related_name='documents', to='main.position', verbose_name='Доступные должности'),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='allowed_positions',
            field=models.ManyToManyField(blank=True, related_name='allowed_document_categories', to='main.position', verbose_name='Доступные должности'),
        ),
    ]
