# Generated by Django 5.1.2 on 2025-10-12 02:00

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_document_allowed_positions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description_ru', models.TextField()),
                ('description_kk', models.TextField()),
                ('description_en', models.TextField()),
                ('icon', models.FileField(upload_to='services/icons/', validators=[main.models.validate_svg_or_image])),
                ('url', models.URLField(blank=True, help_text='Ссылка на сервис (может быть внутренней или внешней)')),
            ],
        ),
    ]
