# Generated by Django 5.2.4 on 2025-08-07 10:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_document_description_en_document_description_kk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок (русский)')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Содержание (русский)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (английский)')),
                ('content_en', ckeditor.fields.RichTextField(blank=True, verbose_name='Содержание (английский)')),
                ('title_kk', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (казахский)')),
                ('content_kk', ckeditor.fields.RichTextField(blank=True, verbose_name='Содержание (казахский)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Информация об университете',
                'verbose_name_plural': 'Информация об университете',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
    ]
