# Generated by Django 5.1.2 on 2025-10-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='category',
            field=models.CharField(choices=[('platonus', 'Platonus'), ('helpdesk', 'HelpDesk'), ('documentolog', 'Documentolog'), ('office', 'MS Office'), ('almauni', 'AlmaUni')], default='almauni', max_length=50, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='position',
            name='group',
            field=models.CharField(blank=True, choices=[('it', 'IT'), ('hr', 'HR'), ('aup', 'АУП'), ('pps', 'ППС'), ('buh', 'Бухгалтерия')], max_length=50, null=True, verbose_name='Группа подразделения'),
        ),
    ]
