# Generated by Django 5.2.4 on 2025-08-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_aboutuniversity_documentcategory_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('rector', 'Ректор'), ('prorector', 'Проректор'), ('other', 'Другое')], max_length=50, verbose_name='Должность')),
                ('full_name', models.CharField(max_length=200, verbose_name='Имя и фамилия')),
                ('photo', models.ImageField(blank=True, upload_to='leaders/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Руководитель университета',
                'verbose_name_plural': 'Руководство университета',
                'ordering': ['order', 'role'],
            },
        ),
        migrations.AddField(
            model_name='aboutuniversity',
            name='image',
            field=models.ImageField(blank=True, upload_to='about/', verbose_name='Картинка истории'),
        ),
    ]
