# Generated by Django 5.1.2 on 2025-10-15 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_instruction_category_position_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код категории')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='instructions/category_logos/', verbose_name='Логотип')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория инструкции',
                'verbose_name_plural': 'Категории инструкций',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='position',
            name='group',
            field=models.CharField(blank=True, choices=[('buh', 'Бухгалтерия'), ('it', 'IT'), ('hr', 'HR'), ('manager', 'Менеджеры'), ('pps', 'ППС'), ('lawyers', 'Юристы'), ('top', 'Топ-менеджмент'), ('archive', 'Архив / Канцелярия'), ('science', 'Наука и исследования'), ('ib', 'ИБ'), ('library', 'Библиотека'), ('advisors', 'Эдвайзеры'), ('dean', 'Декан / Академ. декан / Программ'), ('career', 'Карьера и развитие студентов'), ('aup', 'АУП')], max_length=50, null=True, verbose_name='Группа подразделения'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructions', to='main.instructioncategory', verbose_name='Категория'),
        ),
    ]
