# Generated by Django 5.2.4 on 2025-08-07 11:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_leader_aboutuniversity_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст истории')),
                ('image', models.ImageField(blank=True, upload_to='about/', verbose_name='Картинка истории')),
            ],
            options={
                'verbose_name': 'История университета',
                'verbose_name_plural': 'История университета',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст миссии')),
            ],
            options={
                'verbose_name': 'Миссия университета',
                'verbose_name_plural': 'Миссия университета',
            },
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст ценностей')),
            ],
            options={
                'verbose_name': 'Ценности университета',
                'verbose_name_plural': 'Ценности университета',
            },
        ),
        migrations.DeleteModel(
            name='AboutUniversity',
        ),
    ]
