# Generated by Django 5.1.2 on 2025-10-15 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_instructioncategory_alter_position_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructions', to='main.instructioncategory', verbose_name='Категория'),
        ),
    ]
