# Generated by Django 5.2.4 on 2025-08-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_history_mission_values_delete_aboutuniversity'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcategory',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание (English)'),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='description_kk',
            field=models.TextField(blank=True, verbose_name='Описание (Қазақша)'),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (English)'),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='name_kk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (Қазақша)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(blank=True, verbose_name='Ответ (English)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_kk',
            field=models.TextField(blank=True, verbose_name='Ответ (Қазақша)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Вопрос (English)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_kk',
            field=models.CharField(blank=True, max_length=300, verbose_name='Вопрос (Қазақша)'),
        ),
        migrations.AddField(
            model_name='faqcategory',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание (English)'),
        ),
        migrations.AddField(
            model_name='faqcategory',
            name='description_kk',
            field=models.TextField(blank=True, verbose_name='Описание (Қазақша)'),
        ),
        migrations.AddField(
            model_name='faqcategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (English)'),
        ),
        migrations.AddField(
            model_name='faqcategory',
            name='name_kk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (Қазақша)'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Текст (English)'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='description_kk',
            field=models.TextField(blank=True, verbose_name='Текст (Қазақша)'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (English)'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='title_kk',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (Қазақша)'),
        ),
        migrations.AddField(
            model_name='process',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Текст (English)'),
        ),
        migrations.AddField(
            model_name='process',
            name='description_kk',
            field=models.TextField(blank=True, verbose_name='Текст (Қазақша)'),
        ),
        migrations.AddField(
            model_name='process',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (English)'),
        ),
        migrations.AddField(
            model_name='process',
            name='title_kk',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (Қазақша)'),
        ),
    ]
