# Generated by Django 5.2.4 on 2025-08-11 09:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_documentcategory_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('address_en', models.CharField(blank=True, max_length=255, verbose_name='Адрес (English)')),
                ('address_kk', models.CharField(blank=True, max_length=255, verbose_name='Адрес (Қазақша)')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('campus_items', models.TextField(help_text='Список пунктов через перевод строки', verbose_name='Кампус — пункты')),
                ('campus_items_en', models.TextField(blank=True, verbose_name='Кампус — пункты (English)')),
                ('campus_items_kk', models.TextField(blank=True, verbose_name='Кампус — пункты (Қазақша)')),
            ],
            options={
                'verbose_name': 'Контакты и карта',
                'verbose_name_plural': 'Контакты и карта',
            },
        ),
        migrations.AddField(
            model_name='history',
            name='text_en',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст истории (English)'),
        ),
        migrations.AddField(
            model_name='history',
            name='text_kk',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст истории (Қазақша)'),
        ),
        migrations.AddField(
            model_name='mission',
            name='text_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='Текст миссии (English)'),
        ),
        migrations.AddField(
            model_name='mission',
            name='text_kk',
            field=models.CharField(blank=True, max_length=500, verbose_name='Текст миссии (Қазақша)'),
        ),
        migrations.AddField(
            model_name='values',
            name='text_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='Текст ценностей (English)'),
        ),
        migrations.AddField(
            model_name='values',
            name='text_kk',
            field=models.CharField(blank=True, max_length=500, verbose_name='Текст ценностей (Қазақша)'),
        ),
    ]
