# Generated by Django 5.2.4 on 2025-08-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_contactinfo_history_text_en_history_text_kk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название урока')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Название (English)')),
                ('title_kk', models.CharField(blank=True, max_length=200, verbose_name='Название (Қазақша)')),
                ('description', models.TextField(verbose_name='Описание урока')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (English)')),
                ('description_kk', models.TextField(blank=True, verbose_name='Описание (Қазақша)')),
                ('video', models.FileField(blank=True, help_text='Поддерживаемые форматы: MP4, AVI, MOV, WMV', null=True, upload_to='lessons/videos/', verbose_name='Видео файл')),
                ('pdf_file', models.FileField(blank=True, help_text='PDF файл будет автоматически конвертирован в слайды', null=True, upload_to='lessons/pdfs/', verbose_name='PDF файл')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Примерная длительность урока в минутах', null=True, verbose_name='Длительность (минуты)')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20, verbose_name='Уровень сложности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['-created_at'],
            },
        ),
    ]
