# Generated by Django 5.2.4 on 2025-08-18 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завершения')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson', verbose_name='Урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Завершение урока',
                'verbose_name_plural': 'Завершения уроков',
                'ordering': ['-completed_at'],
                'unique_together': {('lesson', 'user')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='completed_by',
            field=models.ManyToManyField(related_name='completed_lessons', through='main.LessonCompletion', to=settings.AUTH_USER_MODEL, verbose_name='Завершившие пользователи'),
        ),
    ]
