# Generated by Django 5.2.4 on 2025-08-18 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_lessoncompletion_lesson_completed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_progress', models.PositiveIntegerField(default=0, verbose_name='Прогресс видео (сек)')),
                ('video_watched', models.BooleanField(default=False, verbose_name='Видео просмотрено')),
                ('pdf_current_page', models.PositiveIntegerField(default=1, verbose_name='Текущая страница PDF')),
                ('pdf_total_pages', models.PositiveIntegerField(default=1, verbose_name='Всего страниц PDF')),
                ('pdf_completed', models.BooleanField(default=False, verbose_name='PDF пролистан до конца')),
                ('is_ready_to_complete', models.BooleanField(default=False, verbose_name='Готов к завершению')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson', verbose_name='Урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс урока',
                'verbose_name_plural': 'Прогресс уроков',
                'ordering': ['-updated_at'],
                'unique_together': {('lesson', 'user')},
            },
        ),
    ]
