# Generated by Django 4.2.7 on 2025-08-19 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_lessonprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Название (English)')),
                ('name_kk', models.CharField(blank=True, max_length=100, verbose_name='Название (Қазақша)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (English)')),
                ('description_kk', models.TextField(blank=True, verbose_name='Описание (Қазақша)')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория уроков',
                'verbose_name_plural': 'Категории уроков',
                'ordering': ['order_index', 'name'],
            },
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='completed_by',
            new_name='completed_users',
        ),
        migrations.AddField(
            model_name='lesson',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.lessoncategory', verbose_name='Категория'),
        ),
    ]
