# Generated by Django 5.2.4 on 2025-08-21 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_lessoncategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lessons/slides/', verbose_name='Изображение слайда')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название слайда')),
                ('description', models.TextField(blank=True, verbose_name='Описание слайда')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='main.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Слайд урока',
                'verbose_name_plural': 'Слайды уроков',
                'ordering': ['lesson', 'order'],
                'unique_together': {('lesson', 'order')},
            },
        ),
    ]
