# Generated by Django 5.2.4 on 2025-08-21 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_lessonslide'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'ordering': ['-last_activity'], 'verbose_name': 'Прогресс урока', 'verbose_name_plural': 'Прогресс уроков'},
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='video_progress',
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='Последняя активность'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='pdf_last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление PDF'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='slides_completed',
            field=models.BooleanField(default=False, verbose_name='Слайды завершены'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='slides_current_slide',
            field=models.PositiveIntegerField(default=1, verbose_name='Текущий слайд'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='slides_last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление слайдов'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='slides_total_slides',
            field=models.PositiveIntegerField(default=1, verbose_name='Всего слайдов'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='video_current_time',
            field=models.FloatField(default=0.0, verbose_name='Текущее время видео (секунды)'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='video_last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление видео'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='video_total_time',
            field=models.FloatField(default=0.0, verbose_name='Общее время видео (секунды)'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='main.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='pdf_completed',
            field=models.BooleanField(default=False, verbose_name='PDF/слайды завершены'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
