# Generated by Django 5.2.4 on 2025-08-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_lessonprogress_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='video_max_progress_percent',
            field=models.FloatField(default=0.0, verbose_name='Максимальный прогресс видео (%)'),
        ),
    ]
