# Generated by Django 5.2.4 on 2025-08-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_lessonprogress_video_max_progress_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='duration',
        ),
    ]
