# Generated by Django 5.2.4 on 2025-08-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_duration_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название урока'),
        ),
    ]
