# Generated by Django 5.2.4 on 2025-08-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_add_unique_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='slides_max_progress_percent',
            field=models.FloatField(default=0.0, verbose_name='Максимальный прогресс слайдов (%)'),
        ),
    ]
