# Generated by Django 5.2.4 on 2025-08-28 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_add_slides_max_progress_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное имя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='Кафедра/Отдел')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('can_create_lessons', models.BooleanField(default=True, verbose_name='Может создавать уроки')),
                ('can_edit_lessons', models.BooleanField(default=True, verbose_name='Может редактировать уроки')),
                ('can_delete_lessons', models.BooleanField(default=False, verbose_name='Может удалять уроки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Редактор',
                'verbose_name_plural': 'Редакторы',
                'ordering': ['full_name'],
            },
        ),
    ]
