# Generated by Django 4.2.7 on 2025-08-28 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0024_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editor',
            name='can_create_lessons',
        ),
        migrations.RemoveField(
            model_name='editor',
            name='can_delete_lessons',
        ),
        migrations.RemoveField(
            model_name='editor',
            name='can_edit_lessons',
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Редактор или администратор, создавший урок', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор урока'),
        ),
    ]
