# Generated by Django 5.2.4 on 2025-09-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_lesson_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='campus_image',
            field=models.ImageField(blank=True, help_text="Изображение отображается на странице 'Контакты и карта' в разделе 'Кампус'", null=True, upload_to='campus/', verbose_name='Изображение кампуса'),
        ),
    ]
