# Generated by Django 5.2.4 on 2025-09-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_add_campus_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='campus_3d_button_text',
            field=models.CharField(blank=True, default='Изучить кампус в 3D', help_text='Текст, который отображается на кнопке для 3D просмотра кампуса', max_length=200, verbose_name='Текст кнопки 3D кампуса'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='campus_3d_button_text_en',
            field=models.CharField(blank=True, help_text='Текст кнопки на английском языке', max_length=200, verbose_name='Текст кнопки 3D кампуса (English)'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='campus_3d_button_text_kk',
            field=models.CharField(blank=True, help_text='Текст кнопки на казахском языке', max_length=200, verbose_name='Текст кнопки 3D кампуса (Қазақша)'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='campus_3d_enabled',
            field=models.BooleanField(default=False, help_text='Включить/выключить отображение кнопки 3D кампуса на сайте', verbose_name='Показывать кнопку 3D кампуса'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='campus_3d_url',
            field=models.URLField(blank=True, help_text='URL для 3D просмотра кампуса (например, виртуальный тур)', verbose_name='Ссылка на 3D кампус'),
        ),
    ]
