# Generated by Django 5.2.4 on 2025-09-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_add_campus_3d_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='text',
            field=models.TextField(help_text='Простой текст истории университета', verbose_name='Текст истории'),
        ),
        migrations.AlterField(
            model_name='history',
            name='text_en',
            field=models.TextField(blank=True, help_text='University history text in English', verbose_name='Текст истории (English)'),
        ),
        migrations.AlterField(
            model_name='history',
            name='text_kk',
            field=models.TextField(blank=True, help_text='Университет тарихының мәтіні қазақ тілінде', verbose_name='Текст истории (Қазақша)'),
        ),
    ]
