# Generated by Django 5.2.4 on 2025-09-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_change_history_text_to_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_support_url', models.URLField(blank=True, help_text='URL для IT поддержки (например, система helpdesk)', verbose_name='Ссылка на IT поддержку')),
                ('it_support_enabled', models.BooleanField(default=True, help_text='Включить/выключить отображение кнопки IT поддержки', verbose_name='Показывать кнопку IT поддержки')),
            ],
            options={
                'verbose_name': 'Настройки обратной связи',
                'verbose_name_plural': 'Настройки обратной связи',
            },
        ),
    ]
