# Generated by Django 5.2.4 on 2025-09-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_add_feedback_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('suggestion', 'Предложение'), ('question', 'Вопрос')], max_length=20, verbose_name='Тип обращения'),
        ),
    ]
