# Generated by Django 5.2.4 on 2025-09-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_feedback_feedback_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackSettings',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('suggestion', 'Предложение'), ('complaint', 'Жалоба'), ('question', 'Вопрос'), ('site_issue', 'Проблема с сайтом')], max_length=20, verbose_name='Тип обращения'),
        ),
    ]
