# Generated by Django 5.2.4 on 2025-09-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_feedback_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='it_support_enabled',
            field=models.BooleanField(default=True, help_text='Включить/выключить отображение кнопки IT поддержки на странице обратной связи', verbose_name='Показывать кнопку IT поддержки'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='it_support_url',
            field=models.URLField(blank=True, help_text='URL для IT поддержки (например, система helpdesk)', verbose_name='Ссылка на IT поддержку'),
        ),
    ]
