# Generated by Django 5.2.4 on 2025-09-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_set_fixed_lesson_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='difficulty_level',
        ),
    ]
